theme: minima
title: NanaAssistant
description: Nana is a smart personal assistant to talk with.
minima:
  skin: auto
  social_links
    - { platform: github,  user_url: "https://github.com/NanaAssistant/" }